### ISSUE TITLE
Client build: legacy bundle missing some polyfills

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/install#20]
There have been several cases of older browsers not receiving some polyfills. For example, `Object.fromEntries` is not included in the legacy bundle. This came to our attention when a user running our website on **Chrome 72** got a reference error when our code attempted to use that function.

The current theory is that Chrome 72 is not being targeted by our legacy browserslist query: 
```
[legacy]
> 1%
```

A potential solution is to change this to something like
```
[legacy]
> 0%, not dead
```

To test, run `npx browserslist "QUERY"` to see what browsers are matched.

**Comment by dmfalke** [comment]
https://veupathdb.org/awstats/awstats.pl can be used for guidance on what browser versions our users are actively using.

**Comment by jernestmyers** [comment]
@dmfalke @jtlong3rd Okay, so I tested the legacy bundle in my freshly-minted dev site. Here are the results:

```
|         query         |    du -s site-client.bundle.js    |    du -s    |
|         > 0%          |    10692                          |    90412    |
|    > 0%, not dead     |    10696                          |    90416    |
|    > 1% (current)     |    10660                          |    90372    |
```
